version: "3.8"
services:
  php:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php_app
    volumes:
      - ./src:/var/www/public
    networks:
      - app-network
    environment:
      PHP_IDE_CONFIG: serverName=Docker
    restart: unless-stopped
  nginx:
    image: nginx:latest
    container_name: nginx_app
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/public
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network
    restart: unless-stopped
  mariadb:
    image: mariadb:latest
    container_name: mariadb_app
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: php_login
    ports:
      - 3306:3306
    depends_on:
      - php
    networks:
      - app-network
    restart: unless-stopped
networks:
  app-network:
    driver: bridge

